### ISSUE TITLE
The property `quarkus.operator-sdk.crd.apply` is ignored

### ISSUE THREAD

**Issue by Sgitario** [quarkiverse/quarkus-operator-sdk#242]
## How to reproduce?
You can reproduce this issue by using the [samples/joke](https://github.com/quarkiverse/quarkus-operator-sdk/tree/main/samples/joke) example:
1. `cd samples/joke`
2. mvn clean install -Dquarkus.operator-sdk.crd.apply=true

The auto-generated JokeRequest CRD is not installed.

## Problem
I think that the problem is that this is done when creating an instance of the `Operator` (see https://github.com/quarkiverse/quarkus-operator-sdk/blob/main/core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java#L37). Therefore, this won't ever be applied at build time, but only at runtime when injecting the `Operator`.

**Comment by metacosm** [comment]
The property is not ignored, but, indeed, it only works for dev mode on purpose (because applying a CRD automatically to a cluster is probably not a good idea when you're not developing your operator). It doesn't do anything if the operator is not running. Applying the CRD without the operator running would actually require to spawn a separate process, which, granted, could be done during the build.

**Comment by Sgitario** [comment]
Ok, so I would add a comment in the property to state that this is only intended to work on DEV mode.

**Comment by metacosm** [comment]
Do you think it would make sense to convert this issue into a feature request to support application of the CRD at build time? If not, we should close this issue.

**Comment by Sgitario** [comment]
> Do you think it would make sense to convert this issue into a feature request to support application of the CRD at build time? If not, we should close this issue.

From my point of view, the CRD should always be applied/updated when running the application on DEV mode, otherwise is not guaranteed that the CRD is up to date with what the CRD that has been just auto-generated. 

So, when users use this property to the Maven command, I'd expect that the CRD is always applied even when I'm not running the application on DEV mode. 

In summary, I'd be ok to convert this issue into a feature request.

**Comment by metacosm** [comment]
> > Do you think it would make sense to convert this issue into a feature request to support application of the CRD at build time? If not, we should close this issue.
> 
> From my point of view, the CRD should always be applied/updated when running the application on DEV mode, otherwise is not guaranteed that the CRD is up to date with what the CRD that has been just auto-generated.

This is indeed a valid point. Maybe I should just convert the default to `true` and people who absolutely do not want this feature could turn it off.

> So, when users use this property to the Maven command, I'd expect that the CRD is always applied even when I'm not running the application on DEV mode.
> 
> In summary, I'd be ok to convert this issue into a feature request.

👍🏼

**Comment by metacosm** [comment]
Reverting this change because it doesn't really make sense to apply the CRD to the cluster that's available at build time as opposed to runtime. Also, this causes the CRD to be applied several times at the moment, which is inefficient. Revert commit: https://github.com/quarkiverse/quarkus-operator-sdk/pull/475/commits/e8645189e2989f5fea5723ea9595113c72870c22
