### ISSUE TITLE
 [Question] Is it possible to have managed dependent annotation in other CustomResourceDependent class?

### ISSUE THREAD

**Issue by juangon** [quarkiverse/quarkus-operator-sdk#352]
Hi again!

AFAIK, managed custom resource dependents should be added in the @ControllerConfiguration annotation within a controller.

As I have multiple resources I wouldn't like to have to implement a custom resource (so I can have @ControllerConfiguration) for each of these dependents. 

Is it possible to add "@Dependent" annotations in the CRUKubernetesDependentResource classes so I don't have to implement more unneeded controllers?

Thanks!

**Comment by metacosm** [comment]
I'm not sure I'm following what you're trying to achieve… You need to have one `Reconciler` implementation per primary resource type (i.e. the type of resource your operator manages). Dependents manage secondary resources that your reconciler needs to handle in order to realise the desired state described by your primary resource. You can annotate your `Reconciler` with dependent annotations to have managed dependents to tell JOSDK which secondary resources your reconciler needs to handle and how. Each dependent is associated with a `DependentResource` implementation that can be more or less complex depending on your needs and `CRUKubernetesDependentResource` is one such convenient implementation that takes care of a lot of what you'd need to implement for a typical Kubernetes resource.

You can see an example of how things are wired at https://github.com/quarkiverse/quarkus-operator-sdk/blob/5dc8476af4510b80e922810b147994a63ec16f88/samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/MySQLSchemaReconciler.java#L22-L27

Let me know if you need more information.

**Comment by juangon** [comment]
Thanks @metacosm . So, as far a I undertand, implement custom reconciler only makes sense when having CRD right? In my case I have many resources that doesn't need to be CRD, because they are "core" Kubernetes like deployments, services etc. But I need one custom CRD, which is a secondary resource from other primary, to have dependents too. So in that use case I can have multiple levels of dependencies (like a tree).

I would like to have managed dependents in other dependents like this:

```
@Dependent (DeploymentDependent.class...
public class PrimaryDependent  extends
CRUKubernetesDependentResource<Secondary,Primary>
```
Do you think could be possible? I don't need a Reconciler here as I don't need a custom CRD for DeploymentDependent..

Thanks!

**Comment by csviri** [comment]
@juangon the best practice is to implement reconciler for each CRD, see second point:
https://sdk.operatorframework.io/docs/best-practices/best-practices/

DISCLAIMER: not sure if I understand the question. But if you have a tree, that does not sound good. It is probably more controller you need at the end.

**Comment by juangon** [comment]
Yes but in this case I don`t have CRD. I just need "n" dependent resources (not custom, just core Kubernetes) that are dependents from OTHER dependents too (CRUKubernetesDependent).

Did I explain properly?

**Comment by csviri** [comment]
Could you explain the problem you are solving with the operator? What exactly you want to achieve? Can you be more concrete?

The dependent resources are just at the end resources you want to menage for a custom resource (or ordinary k8s resources also supported). If there are resources that a further dependent on those resources, those need a separate controller.

**Comment by juangon** [comment]
``` 
If there are resources that a further dependent on those resources, those need a separate controller.
``` 

Ok I think this sentence says it all. Thanks!

**Comment by juangon** [comment]
A controller requires a CRD, right?

**Comment by csviri** [comment]
A controller can manage custom resources (that requires CRD), but well known kubernetes onces (like Ingress, ConfigMap) those does not require a CRD.
