### ISSUE TITLE
[Question] Is it possible getting multiple secondary resources having the same class?

### ISSUE THREAD

**Issue by juangon** [quarkiverse/quarkus-operator-sdk#355]
Hi!

In order to "save" reconcilers I would like to have multiple secondary resources (mostly Service and Deployment) for the same primary resource, but the API just let getting secondary resources by class name.

Is it possible this approach with current operator sdk?

Thanks!

**Comment by metacosm** [comment]
What do you mean by "save" reconcilers?
Otherwise, you can get all secondary resources of the same type from:

https://github.com/java-operator-sdk/java-operator-sdk/blob/a7b819bfeebf73795453494b3b478367ae8a3121/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Context.java#L17-L19

Presumably, you have some way to distinguish between the different instances of the same resource types so you can iterate over that set to find the one you're looking for. 

Alternatively, if you know the name of the associated event source, you can also use: 

https://github.com/java-operator-sdk/java-operator-sdk/blob/a7b819bfeebf73795453494b3b478367ae8a3121/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Context.java#L20
