### ISSUE TITLE
Figure out if CsvManifestsBuilder.handleClusterPermission correct

### ISSUE THREAD

**Issue by metacosm** [quarkiverse/quarkus-operator-sdk#477]
The `groupToCRInfo` structure processing seems to have been removed during the work leading to #246. We should figure out whether this is still needed and if not, remove the associated code.

**Comment by Sgitario** [comment]
To be precise, the `groupToCRInfo` was commented out in https://github.com/quarkiverse/quarkus-operator-sdk/pull/294 and then removed by a later pull request. 

Then, the remaining and unused `groupToCRInfo` map is only used in https://github.com/quarkiverse/quarkus-operator-sdk/blob/bd74e006dc02ee1adb236c27085ae047bc3ac156/bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java#L345. 

Note that I'm quite unfamiliar with the logic of this method `CsvManifestsBuilder.handleClusterPermission`, but it was done to fix this issue https://github.com/quarkiverse/quarkus-operator-sdk/issues/145. I tried to reproduce this issue and it's working fine with the changes in the main, so I guess we can remove the associated code: https://github.com/quarkiverse/quarkus-operator-sdk/pull/479

**Comment by metacosm** [comment]
This logic was used to deal with possible roles / bindings in a provided `kubernetes.yml` fragment, iirc, so I'm not sure we can actually remove it and the associated use case might not be working properly at the moment.

**Comment by Sgitario** [comment]
If so, I doubt the logic ever worked as intended because it was using the rules from any cluster rule found in the provided `kubernetes.yml` (it should use only the cluster rule with a matching rule with the same service binding name). 
Even though after https://github.com/quarkiverse/quarkus-operator-sdk/pull/246, we can provide the rules directly in the CSVMetadata annotation, I think the use case you mention It's a nice one to support (code, test, and document), but I would recommend doing it from zero, and without using the `groupToCRInfo` structure.
