### ISSUE TITLE
[doc] quarkus.operator-sdk.controllers."controllers".namespaces is duplicated

### ISSUE THREAD

**Issue by afalhambra-hivemq** [quarkiverse/quarkus-operator-sdk#574]
`quarkus.operator-sdk.controllers."controllers".namespaces` is duplicated in the latest [doc](https://quarkiverse.github.io/quarkiverse-docs/quarkus-operator-sdk/dev/index.html#extension-configuration-reference) leading to confusion since in one row this property is marked with the "lock" icon (i.e. build time property) whereas in the duplicated one there is no lock at all.

My understanding is that this property is at runtime, so this doc needs to be fixed.

**Comment by metacosm** [comment]
Hi @afalhambra-hivemq,

> `quarkus.operator-sdk.controllers."controllers".namespaces` is duplicated in the latest [doc](https://quarkiverse.github.io/quarkiverse-docs/quarkus-operator-sdk/dev/index.html#extension-configuration-reference) leading to confusion since in one row this property is marked with the "lock" icon (i.e. build time property) whereas in the duplicated one there is no lock at all.

This is actually something that is a little weird in the extension. The property is actually processed twice because it is useful to have it at build time (to generate RBACs for example) but might be overridden at runtime (with the understanding that whatever got generated at build time might therefore become wrong). This is why the property is duplicated in the documentation. Note also that the documentation is automatically generated so "fixing" the generated doc will be reverted during the next build. 

I'm looking into options to clean this weirdness up but this will probably require a behavioural change so this will need to occur in a future major release.

**Comment by afalhambra-hivemq** [comment]
mm, ok, thanks for the explanation. Indeed it does look weird and leads to misunderstanding to be honest.

So can I assume there is no drawback if I want to override this property at runtime? appreciate your inputs
