### ISSUE TITLE
ControllerConfiguration itemStore seems ignored

### ISSUE THREAD

**Issue by shawkins** [quarkiverse/quarkus-operator-sdk#780]
When using something like

```
@ControllerConfiguration(itemStore = MyStore.class)
```

context.getControllerConfiguration().getItemStore() is empty.

**Comment by shawkins** [comment]
The issue seems to be that itemStore is tracked by DefaultResourceConfiguration, but the quarkus layer is using configuration interfaces which do not include the itemStore.

cc @csviri

**Comment by metacosm** [comment]
This is actually not well designed at the JOSDK level either because it's not even possible to use the default implementations that are provided from the `@ControllerConfiguration` annotation either (as this would require a no-arg constructor on the implementation classes, which they don't provide) so this probably needs to be addressed in JOSDK, first.

**Comment by csviri** [comment]
When using annotations it is limited in that regard yes ATM. If there is no default constructor simple the override can be used atm

**Comment by shawkins** [comment]
Thank you for the quick fix @metacosm 

Hopefully the next version we align to will contain this.
